<a href="https://colab.research.google.com/github/Monisha1205/google_colab_quanqual/blob/main/ASSESSMENT_PRACTICAL_DATA_ANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # 3. practical tasks
 # A. identify data types

 # 1. Classify each column as Qualitative (Categorical) or Quantitative (Numerical).

In [2]:
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Online_Store_Orders.csv to Online_Store_Orders.csv

In [4]:
dataset = pd.read_csv("/content/Online_Store_Orders.csv")

In [5]:
dataset.head()

,Order_ID,Customer,City,Age,Product_Category,Order_Value,Quantity,Delivery_Days,Rating
0,1001,Arun,Chennai,22,Electronics,2450,2,3,4
1,1002,Priya,Madurai,29,Clothing,1800,3,5,4
2,1003,Rahul,Chennai,35,Electronics,5200,1,4,5
3,1004,Divya,Coimbatore,24,Beauty,1250,2,6,3
4,1005,Karthik,Trichy,41,Home,3100,4,3,4

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          40 non-null     int64
 1   Customer          40 non-null     object
 2   City              40 non-null     object
 3   Age               40 non-null     int64
 4   Product_Category  40 non-null     object
 5   Order_Value       40 non-null     int64
 6   Quantity          40 non-null     int64
 7   Delivery_Days     40 non-null     int64
 8   Rating            40 non-null     int64
dtypes: int64(6), object(3)
memory usage: 2.9+ KB

In [7]:
def quanqual(dataset):
  quan = []
  qual = []
  for ch in  dataset.columns:
    if dataset[ch].dtype == "O":
      #print("qual")
      qual.append(ch)
    else:
      #print("quan")
      quan.append(ch)
  return quan,qual

In [8]:
quan, qual = quanqual(dataset)

# Answer

In [9]:
quan # Quantitative (Numerical)

['Order_ID', 'Age', 'Order_Value', 'Quantity', 'Delivery_Days', 'Rating']

In [10]:
qual  # Qualitative (Categorical)

['Customer', 'City', 'Product_Category']

# 2 . Among the quantitative columns, identify which are Discrete and which are Continuous, where appropriate.

**Answer**

In [11]:
# Order_ID , Order value , Quantity , Delivery_Days , Rating - Discrete
# Age - Continuous

# 3. Identify at least one nominal categorical variable and explain why.

**Answer**

In [12]:
dataset["City"].unique() # city - 'Chennai', 'Madurai', 'Coimbatore', 'Trichy'

array(['Chennai', 'Madurai', 'Coimbatore', 'Trichy'], dtype=object)

In [13]:
dataset["Product_Category"].unique()# product category - 'Electronics', 'Clothing', 'Beauty', 'Home'

array(['Electronics', 'Clothing', 'Beauty', 'Home'], dtype=object)

In [14]:
# Nominal categorical
'''  1. Categories cannot be sorted from low to high or best to worst.
     2. Each item fits into only one category.
     3. Nominal data is a type of categorical data that labels or sorts
      items into distinct, non-overlapping groups without any natural order, rank, or numerical value '''
''' We cannot be sorted from low to high in the given dataset have city and product category that why
 this is comes under nominal dataset'''

' We cannot be sorted from low to high in the given dataset have city and product category that why\n this is comes under nominal dataset'

# B. Frequency Analysis

# 4. Create a frequency table for Product_Category showing Category, Frequency, and Percentage.

**Answer**

In [15]:
qual

['Customer', 'City', 'Product_Category']

In [16]:
dataset[qual[2]].unique()

array(['Electronics', 'Clothing', 'Beauty', 'Home'], dtype=object)

In [17]:
dataset[qual[2]].value_counts()

Product_Category
Electronics    11
Clothing       10
Home           10
Beauty          9
Name: count, dtype: int64

In [18]:
dataset.shape[0]

40

In [19]:
Freq_table = pd.DataFrame(columns=("unique_Category", "frequency", "relative_frequency", "cumsum"))
Freq_table["unique_Category"] = dataset["Product_Category"].unique()
Freq_table["frequency"] = dataset["Product_Category"].value_counts().values
Freq_table["relative_frequency"] = (Freq_table["frequency"]/dataset.shape[0])* 100
Freq_table["cumsum"] = Freq_table["relative_frequency"].cumsum()

In [20]:
Freq_table

  unique_Category  frequency  relative_frequency  cumsum
0     Electronics         11                27.5    27.5
1        Clothing         10                25.0    52.5
2          Beauty         10                25.0    77.5
3            Home          9                22.5   100.0

# 5. Create a frequency table for City showing Frequency and Percentage.

**Answer**

In [21]:
for ColumnsName in qual:
  Freq_table = pd.DataFrame(columns=("unique_Category", "frequency", "relative_frequency", "cumsum"))
  Freq_table["unique_Category"] = dataset[ColumnsName].unique()
  Freq_table["frequency"] = dataset[ColumnsName].value_counts().values
  Freq_table["relative_frequency"] = (Freq_table["frequency"]/dataset.shape[0])* 100
  Freq_table["cumsum"] = Freq_table["relative_frequency"].cumsum()
  print("\nFrequency Table for:", ColumnsName)
  print(Freq_table)

Frequency Table for: Customer
  unique_Category  frequency  relative_frequency  cumsum
0            Arun          4                10.0    10.0
1           Priya          4                10.0    20.0
2           Rahul          4                10.0    30.0
3           Divya          4                10.0    40.0
4         Karthik          4                10.0    50.0
5           Meena          4                10.0    60.0
6          Sanjay          4                10.0    70.0
7           Aisha          4                10.0    80.0
8           Vijay          4                10.0    90.0
9           Nisha          4                10.0   100.0

Frequency Table for: City
  unique_Category  frequency  relative_frequency  cumsum
0         Chennai         12                30.0    30.0
1         Madurai         10                25.0    55.0
2      Coimbatore          9                22.5    77.5
3          Trichy          9                22.5   100.0

Frequency Table for: Product_Category
  unique_Category  frequency  relative_frequency  cumsum
0     Electronics         11                27.5    27.5
1        Clothing         10                25.0    52.5
2          Beauty         10                25.0    77.5
3            Home          9                22.5   100.0

# 6. Find the most frequently occurring Product_Category.

**answer**

In [22]:
# The frequency table shows that Electronics products are sold most frequently.

# 7. Create a frequency table for Rating (1–5).  Which rating occurs most often?

**Answer**

In [23]:
for ColumnsName in quan:
  Freq_table = pd.DataFrame(columns=("unique_frequency", "frequency", "relative_frequency", "cumsum"))
  Freq_table["unique_frequency"] = dataset[ColumnsName].unique()
  Freq_table["frequency"] = dataset[ColumnsName].value_counts().values
  Freq_table["relative_frequency"] = (Freq_table["frequency"]/dataset.shape[0])* 100
  Freq_table["cumsum"] = Freq_table["relative_frequency"].cumsum()
  print("\nFrequency Table for:", ColumnsName)
  print(Freq_table)

Frequency Table for: Order_ID
    unique_frequency  frequency  relative_frequency  cumsum
0               1001          1                 2.5     2.5
1               1002          1                 2.5     5.0
2               1003          1                 2.5     7.5
3               1004          1                 2.5    10.0
4               1005          1                 2.5    12.5
5               1006          1                 2.5    15.0
6               1007          1                 2.5    17.5
7               1008          1                 2.5    20.0
8               1009          1                 2.5    22.5
9               1010          1                 2.5    25.0
10              1011          1                 2.5    27.5
11              1012          1                 2.5    30.0
12              1013          1                 2.5    32.5
13              1014          1                 2.5    35.0
14              1015          1                 2.5    37.5
15              1016          1                 2.5    40.0
16              1017          1                 2.5    42.5
17              1018          1                 2.5    45.0
18              1019          1                 2.5    47.5
19              1020          1                 2.5    50.0
20              1021          1                 2.5    52.5
21              1022          1                 2.5    55.0
22              1023          1                 2.5    57.5
23              1024          1                 2.5    60.0
24              1025          1                 2.5    62.5
25              1026          1                 2.5    65.0
26              1027          1                 2.5    67.5
27              1028          1                 2.5    70.0
28              1029          1                 2.5    72.5
29              1030          1                 2.5    75.0
30              1031          1                 2.5    77.5
31              1032          1                 2.5    80.0
32              1033          1                 2.5    82.5
33              1034          1                 2.5    85.0
34              1035          1                 2.5    87.5
35              1036          1                 2.5    90.0
36              1037          1                 2.5    92.5
37              1038          1                 2.5    95.0
38              1039          1                 2.5    97.5
39              1040          1                 2.5   100.0

Frequency Table for: Age
   unique_frequency  frequency  relative_frequency  cumsum
0                22          4                10.0    10.0
1                29          4                10.0    20.0
2                35          4                10.0    30.0
3                24          4                10.0    40.0
4                41          4                10.0    50.0
5                31          4                10.0    60.0
6                27          4                10.0    70.0
7                23          4                10.0    80.0
8                38          4                10.0    90.0
9                26          4                10.0   100.0

Frequency Table for: Order_Value
    unique_frequency  frequency  relative_frequency  cumsum
0               2450          2                 5.0     5.0
1               1800          2                 5.0    10.0
2               5200          1                 2.5    12.5
3               1250          1                 2.5    15.0
4               3100          1                 2.5    17.5
5               2200          1                 2.5    20.0
6               2750          1                 2.5    22.5
7                950          1                 2.5    25.0
8               4800          1                 2.5    27.5
9               1650          1                 2.5    30.0
10              2950          1                 2.5    32.5
11              3400          1                 2.5    35.0
12              2100          1                 2.5    37.5
13              1100          1                 2.5    40.0
14              6100          1                 2.5    42.5
15              2850          1                 2.5    45.0
16              1950          1                 2.5    47.5
17              1350          1                 2.5    50.0
18              4550          1                 2.5    52.5
19              3200          1                 2.5    55.0
20              1750          1                 2.5    57.5
21              1450          1                 2.5    60.0
22              5300          1                 2.5    62.5
23              2600          1                 2.5    65.0
24              2300          1                 2.5    67.5
25              1200          1                 2.5    70.0
26              4950          1                 2.5    72.5
27              3050          1                 2.5    75.0
28              2050          1                 2.5    77.5
29              1050          1                 2.5    80.0
30              3600          1                 2.5    82.5
31              2400          1                 2.5    85.0
32              1300          1                 2.5    87.5
33              6800          1                 2.5    90.0
34              1850          1                 2.5    92.5
35              1150          1                 2.5    95.0
36              5100          1                 2.5    97.5
37              3300          1                 2.5   100.0

Frequency Table for: Quantity
   unique_frequency  frequency  relative_frequency  cumsum
0                 2         17                42.5    42.5
1                 3         10                25.0    67.5
2                 1          8                20.0    87.5
3                 4          4                10.0    97.5
4                 5          1                 2.5   100.0

Frequency Table for: Delivery_Days
   unique_frequency  frequency  relative_frequency  cumsum
0                 3         10                25.0    25.0
1                 5          9                22.5    47.5
2                 4          7                17.5    65.0
3                 6          7                17.5    82.5
4                 7          4                10.0    92.5
5                 2          3                 7.5   100.0

Frequency Table for: Rating
   unique_frequency  frequency  relative_frequency  cumsum
0                 4         19                47.5    47.5
1                 5         11                27.5    75.0
2                 3         10                25.0   100.0

In [24]:
# rating 4 is occurs more often

# C. Central Tendency

# 8. For Order_Value, calculate Mean, Median, and Mode.
# 9. For Age, calculate Mean, Median, and Mode.
# 10. For Delivery_Days, calculate Mean and Median.

In [25]:
quan

['Order_ID', 'Age', 'Order_Value', 'Quantity', 'Delivery_Days', 'Rating']

In [26]:
descriptive = pd.DataFrame(index = ["Mean", "Median", "Mode"], columns = quan)
for ColumnsName in quan:
  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
  descriptive[ColumnsName]["Mode"]= dataset[ColumnsName].mode()[0]

/tmp/ipykernel_2169/1582507035.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
/tmp/ipykernel_2169/1582507035.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
/tmp/ipykernel_2169/1582507035.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mode"]= dataset[ColumnsName].mode()[0]
/tmp/ipykernel_2169/1582507035.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
/tmp/ipykernel_2169/1582507035.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
/tmp/ipykernel_2169/1582507035.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mode"]= dataset[ColumnsName].mode()[0]
/tmp/ipykernel_2169/1582507035.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
/tmp/ipykernel_2169/1582507035.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
/tmp/ipykernel_2169/1582507035.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mode"]= dataset[ColumnsName].mode()[0]
/tmp/ipykernel_2169/1582507035.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
/tmp/ipykernel_2169/1582507035.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
/tmp/ipykernel_2169/1582507035.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mode"]= dataset[ColumnsName].mode()[0]
/tmp/ipykernel_2169/1582507035.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
/tmp/ipykernel_2169/1582507035.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
/tmp/ipykernel_2169/1582507035.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mode"]= dataset[ColumnsName].mode()[0]
/tmp/ipykernel_2169/1582507035.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
/tmp/ipykernel_2169/1582507035.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
/tmp/ipykernel_2169/1582507035.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mode"]= dataset[ColumnsName].mode()[0]

**Answer**

In [27]:
descriptive

       Order_ID   Age Order_Value Quantity Delivery_Days Rating
Mean     1020.5  29.6      2815.0    2.225         4.425  4.025
Median   1020.5  28.0      2525.0      2.0           4.0    4.0
Mode       1001    22        2750        2             4      4

# 11. Compare Mean and Median for Order_Value. Which one better represents a typical order if extreme values are present? Explain briefly.

**Answer**

In [28]:
descriptive = pd.DataFrame(index = ["Mean", "Median", "Mode", "Min", "25th", "50th", "75th", "Max", "IQR", "1.5IQR", "LowerOutlier", "GreaterOutlier"], columns = quan)
for ColumnsName in quan:
  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
  descriptive[ColumnsName]["Mode"] = dataset[ColumnsName].mode()[0]
  descriptive[ColumnsName]["Min"] = dataset.describe()[ColumnsName]["min"]
  descriptive[ColumnsName]["25th"] = dataset.describe()[ColumnsName]["25%"]
  descriptive[ColumnsName]["50th"] = dataset.describe()[ColumnsName]["50%"]
  descriptive[ColumnsName]["75th"] = dataset.describe()[ColumnsName]["75%"]
  descriptive[ColumnsName]["Max"] = dataset.describe()[ColumnsName]["max"]
  descriptive[ColumnsName]["IQR"] = descriptive[ColumnsName]["75th"] - descriptive[ColumnsName]["25th"]
  descriptive[ColumnsName]["1.5IQR"] = 1.5 * descriptive[ColumnsName]["IQR"]
  descriptive[ColumnsName]["LowerOutlier"] = descriptive[ColumnsName]["25th"] - descriptive[ColumnsName]["1.5IQR"]
  descriptive[ColumnsName]["GreaterOutlier"] = descriptive[ColumnsName]["75th"] + descriptive[ColumnsName]["1.5IQR"]

/tmp/ipykernel_2169/3316622404.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
/tmp/ipykernel_2169/3316622404.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
/tmp/ipykernel_2169/3316622404.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mode"] = dataset[ColumnsName].mode()[0]
/tmp/ipykernel_2169/3316622404.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Min"] = dataset.describe()[ColumnsName]["min"]
/tmp/ipykernel_2169/3316622404.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["25th"] = dataset.describe()[ColumnsName]["25%"]
/tmp/ipykernel_2169/3316622404.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["50th"] = dataset.describe()[ColumnsName]["50%"]
/tmp/ipykernel_2169/3316622404.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["75th"] = dataset.describe()[ColumnsName]["75%"]
/tmp/ipykernel_2169/3316622404.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Max"] = dataset.describe()[ColumnsName]["max"]
/tmp/ipykernel_2169/3316622404.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["IQR"] = descriptive[ColumnsName]["75th"] - descriptive[ColumnsName]["25th"]
/tmp/ipykernel_2169/3316622404.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["1.5IQR"] = 1.5 * descriptive[ColumnsName]["IQR"]
/tmp/ipykernel_2169/3316622404.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["LowerOutlier"] = descriptive[ColumnsName]["25th"] - descriptive[ColumnsName]["1.5IQR"]
/tmp/ipykernel_2169/3316622404.py:14: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["GreaterOutlier"] = descriptive[ColumnsName]["75th"] + descriptive[ColumnsName]["1.5IQR"]
/tmp/ipykernel_2169/3316622404.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mean"] = dataset[ColumnsName].mean()
/tmp/ipykernel_2169/3316622404.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Median"] = dataset[ColumnsName].median()
/tmp/ipykernel_2169/3316622404.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Mode"] = dataset[ColumnsName].mode()[0]
/tmp/ipykernel_2169/3316622404.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Min"] = dataset.describe()[ColumnsName]["min"]
/tmp/ipykernel_2169/3316622404.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["25th"] = dataset.describe()[ColumnsName]["25%"]
/tmp/ipykernel_2169/3316622404.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["50th"] = dataset.describe()[ColumnsName]["50%"]
/tmp/ipykernel_2169/3316622404.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["75th"] = dataset.describe()[ColumnsName]["75%"]
/tmp/ipykernel_2169/3316622404.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["Max"] = dataset.describe()[ColumnsName]["max"]
/tmp/ipykernel_2169/3316622404.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[ColumnsName]["IQR"] = descriptive[ColumnsName]["75th"] - descriptive[ColumnsName]["25th"]
/tmp/ipykernel_2169/3316622404.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value


In [29]:
descriptive

               Order_ID   Age Order_Value Quantity Delivery_Days Rating
Mean             1020.5  29.6      2815.0    2.225         4.425  4.025
Median           1020.5  28.0      2525.0      2.0           4.0    4.0
Mode               1001    22        2750        2             4      4
Min              1001.0  22.0       950.0      1.0           2.0    3.0
25th            1010.75  24.0      1725.0     1.75           3.0   3.75
50th             1020.5  28.0      2525.0      2.0           4.0    4.0
75th            1030.25  35.0      3325.0      3.0          5.25    5.0
Max              1040.0  41.0      6800.0      5.0           7.0    5.0
IQR                19.5  11.0      1600.0     1.25          2.25   1.25
1.5IQR            29.25  16.5      2400.0    1.875         3.375  1.875
LowerOutlier      981.5   7.5      -675.0   -0.125        -0.375  1.875
GreaterOutlier   1059.5  51.5      5725.0    4.875         8.625  6.875

In [30]:
lesser = []
greater = []
for ColumnsNames in quan:
  if descriptive[ColumnsNames]["Min"] < descriptive[ColumnsNames]["LowerOutlier"]:
    lesser.append(ColumnsNames)
  if descriptive[ColumnsNames]["Max"] > descriptive[ColumnsNames]["GreaterOutlier"]:
    greater.append(ColumnsNames)

In [31]:
lesser

[]

In [32]:
greater

['Order_Value', 'Quantity']

In [33]:
# The mean Order_Value is ₹2815.0, while the median Order_Value is ₹2525.0. Since the mean is much higher than the median, this suggests that some extremely high order values are affecting the mean. Therefore, the median better represents a typical order because it is less affected by extreme values (outliers).

# D. Percentile Analysis

# 12. Calculate the 25th percentile (P25) of Order_Value

**Answer**

In [57]:
descriptive["Order_Value"]["25th"]

np.float64(1725.0)

In [34]:
# Based on the calculation performed using the above loop, the 25th percentile value of Order_Value is 1725.0.

# 13. Calculate the 50th percentile (P50) of Order_Value and compare it with the Median.

**Answer**

In [58]:
descriptive["Order_Value"]["50th"]

np.float64(2525.0)

In [59]:
descriptive["Order_Value"]["Median"]

2525.0

In [35]:
# Both P50th and Median are based on the middle position of the data when the values are arranged in ascending order. Therefore, P50th and Median have the same value.

# 14. Calculate the 75th percentile (P75) of Order_Value.

**Answer**

In [60]:
descriptive["Order_Value"]["75th"]

np.float64(3325.0)

In [36]:
# Based on the calculation performed using the above loop, the 75th percentile value of Order_Value is 3325.

# 15. Calculate the 90th percentile (P90) of Order_Value.

**Answer**

In [37]:
dataset["Order_Value"].quantile(0.90)

np.float64(5110.0)

In [37]:
# Based on the above Code, the 90th percentile value of Order_Value is 5110.

# 16. Interpret P75 in one simple business sentence.

**Answer**

In [61]:
descriptive["Order_Value"]["75th"]

np.float64(3325.0)

In [62]:
descriptive["Order_Value"]["Max"] - descriptive["Order_Value"]["75th"] # remaining 25% above the 75%

np.float64(3475.0)

In [37]:
# The 75th percentile of Order_Value is ₹3,325, meaning that 75% of orders have an order value of ₹3,325 or less, while 25% of orders have an order value above ₹3,325.

# E. IQR & Outlier Detection

# 17. Calculate Q1 and Q3 for Order_Value.

**Answer**

In [ ]:
# p25th = Q1
# p50th = Q2
# p75th = Q3
# p100th = Q4

In [64]:
descriptive.iloc[[4,6]]

     Order_ID   Age Order_Value Quantity Delivery_Days Rating
25th  1010.75  24.0      1725.0     1.75           3.0   3.75
75th  1030.25  35.0      3325.0      3.0          5.25    5.0

In [37]:
# Based on the calculation performed using the above loop, the IQR value of Order_Value is 1600.

# 18. Calculate IQR = Q3 − Q1.

In [42]:
display(descriptive.iloc[[8]]) # Interquertile range = Q3 - Q1

    Order_ID   Age Order_Value Quantity Delivery_Days Rating
IQR     19.5  11.0      1600.0     1.25          2.25   1.25

#19. Calculate the Lower Bound and Upper Bound using the 1.5 × IQR rule.

**Answer**

In [43]:
display(descriptive.iloc[[9]])

       Order_ID   Age Order_Value Quantity Delivery_Days Rating
1.5IQR    29.25  16.5      2400.0    1.875         3.375  1.875

# 20 .Identify all Order_Value records that are potential outliers.

**Answer**

In [44]:
greater

['Order_Value', 'Quantity']

In [ ]:
# from the above mentioned Order value and Quantity as greater outliers in this dataset, lower outliers not present.

# 21. Repeat the IQR analysis for Delivery_Days.

**Answer**

In [45]:
descriptive["Delivery_Days"]["IQR"] # IQR analysis for Delivery_Days is 2.25

np.float64(2.25)

In [46]:
descriptive["Delivery_Days"]["1.5IQR"] # 1.5IQR analysis for Delivery_Days is 3.375

np.float64(3.375)

# 22. Write one sentence explaining what an outlier means in this dataset.

**Answer**

In [ ]:
# An outlier is an Order_Value that is unusually high or low compared with most of the other orders in the dataset.

# F. Business Interpretation

In [54]:
for ColumnsName in quan:
  Freq_table = pd.DataFrame(columns=("unique_values", "frequency", "relative_frequency", "cumsum"))
  Freq_table["unique_values"] = dataset[ColumnsName].value_counts().sort_index().index
  Freq_table["frequency"] = dataset[ColumnsName].value_counts().sort_index().values
  Freq_table["relative_frequency"] = Freq_table["frequency"]/dataset.shape[0]
  Freq_table["cumsum"] = round((Freq_table["relative_frequency"].cumsum())*100,2)
  print("\nFrequency Table for:", ColumnsName)
  print(Freq_table)

Frequency Table for: Order_ID
    unique_values  frequency  relative_frequency  cumsum
0            1001          1               0.025     2.5
1            1002          1               0.025     5.0
2            1003          1               0.025     7.5
3            1004          1               0.025    10.0
4            1005          1               0.025    12.5
5            1006          1               0.025    15.0
6            1007          1               0.025    17.5
7            1008          1               0.025    20.0
8            1009          1               0.025    22.5
9            1010          1               0.025    25.0
10           1011          1               0.025    27.5
11           1012          1               0.025    30.0
12           1013          1               0.025    32.5
13           1014          1               0.025    35.0
14           1015          1               0.025    37.5
15           1016          1               0.025    40.0
16           1017          1               0.025    42.5
17           1018          1               0.025    45.0
18           1019          1               0.025    47.5
19           1020          1               0.025    50.0
20           1021          1               0.025    52.5
21           1022          1               0.025    55.0
22           1023          1               0.025    57.5
23           1024          1               0.025    60.0
24           1025          1               0.025    62.5
25           1026          1               0.025    65.0
26           1027          1               0.025    67.5
27           1028          1               0.025    70.0
28           1029          1               0.025    72.5
29           1030          1               0.025    75.0
30           1031          1               0.025    77.5
31           1032          1               0.025    80.0
32           1033          1               0.025    82.5
33           1034          1               0.025    85.0
34           1035          1               0.025    87.5
35           1036          1               0.025    90.0
36           1037          1               0.025    92.5
37           1038          1               0.025    95.0
38           1039          1               0.025    97.5
39           1040          1               0.025   100.0

Frequency Table for: Age
   unique_values  frequency  relative_frequency  cumsum
0             22          4                 0.1    10.0
1             23          4                 0.1    20.0
2             24          4                 0.1    30.0
3             26          4                 0.1    40.0
4             27          4                 0.1    50.0
5             29          4                 0.1    60.0
6             31          4                 0.1    70.0
7             35          4                 0.1    80.0
8             38          4                 0.1    90.0
9             41          4                 0.1   100.0

Frequency Table for: Order_Value
    unique_values  frequency  relative_frequency  cumsum
0             950          1               0.025     2.5
1            1050          1               0.025     5.0
2            1100          1               0.025     7.5
3            1150          1               0.025    10.0
4            1200          1               0.025    12.5
5            1250          1               0.025    15.0
6            1300          1               0.025    17.5
7            1350          1               0.025    20.0
8            1450          1               0.025    22.5
9            1650          1               0.025    25.0
10           1750          1               0.025    27.5
11           1800          1               0.025    30.0
12           1850          1               0.025    32.5
13           1950          1               0.025    35.0
14           2050          1               0.025    37.5
15           2100          1               0.025    40.0
16           2200          1               0.025    42.5
17           2300          1               0.025    45.0
18           2400          1               0.025    47.5
19           2450          1               0.025    50.0
20           2600          1               0.025    52.5
21           2750          2               0.050    57.5
22           2850          1               0.025    60.0
23           2950          2               0.050    65.0
24           3050          1               0.025    67.5
25           3100          1               0.025    70.0
26           3200          1               0.025    72.5
27           3300          1               0.025    75.0
28           3400          1               0.025    77.5
29           3600          1               0.025    80.0
30           4550          1               0.025    82.5
31           4800          1               0.025    85.0
32           4950          1               0.025    87.5
33           5100          1               0.025    90.0
34           5200          1               0.025    92.5
35           5300          1               0.025    95.0
36           6100          1               0.025    97.5
37           6800          1               0.025   100.0

Frequency Table for: Quantity
   unique_values  frequency  relative_frequency  cumsum
0              1         10               0.250    25.0
1              2         17               0.425    67.5
2              3          8               0.200    87.5
3              4          4               0.100    97.5
4              5          1               0.025   100.0

Frequency Table for: Delivery_Days
   unique_values  frequency  relative_frequency  cumsum
0              2          4               0.100    10.0
1              3          7               0.175    27.5
2              4         10               0.250    52.5
3              5          9               0.225    75.0
4              6          7               0.175    92.5
5              7          3               0.075   100.0

Frequency Table for: Rating
   unique_values  frequency  relative_frequency  cumsum
0              3         10               0.250    25.0
1              4         19               0.475    72.5
2              5         11               0.275   100.0

In [55]:
for ColumnsName in qual:
  Freq_table = pd.DataFrame(columns=("unique_values", "frequency", "relative_frequency", "cumsum"))
  Freq_table["unique_values"] = dataset[ColumnsName].value_counts().sort_index().index
  Freq_table["frequency"] = dataset[ColumnsName].value_counts().sort_index().values
  Freq_table["relative_frequency"] = Freq_table["frequency"]/dataset.shape[0]
  Freq_table["cumsum"] = round((Freq_table["relative_frequency"].cumsum())*100,2)
  print("\nFrequency Table for:", ColumnsName)
  print(Freq_table)

Frequency Table for: Customer
  unique_values  frequency  relative_frequency  cumsum
0         Aisha          4                 0.1    10.0
1          Arun          4                 0.1    20.0
2         Divya          4                 0.1    30.0
3       Karthik          4                 0.1    40.0
4         Meena          4                 0.1    50.0
5         Nisha          4                 0.1    60.0
6         Priya          4                 0.1    70.0
7         Rahul          4                 0.1    80.0
8        Sanjay          4                 0.1    90.0
9         Vijay          4                 0.1   100.0

Frequency Table for: City
  unique_values  frequency  relative_frequency  cumsum
0       Chennai         12               0.300    30.0
1    Coimbatore          9               0.225    52.5
2       Madurai         10               0.250    77.5
3        Trichy          9               0.225   100.0

Frequency Table for: Product_Category
  unique_values  frequency  relative_frequency  cumsum
0        Beauty          9               0.225    22.5
1      Clothing         10               0.250    47.5
2   Electronics         11               0.275    75.0
3          Home         10               0.250   100.0

# 23. Which city appears to have the strongest order activity? Support your answer using frequency.

**Answer**

In [47]:
dataset["City"].value_counts()

City
Chennai       12
Madurai       10
Coimbatore     9
Trichy         9
Name: count, dtype: int64

In [ ]:
# Chennai as higher order compare to other citys

#24. Which product category appears most popular?

**Answer**

In [49]:
dataset["Product_Category"].value_counts()

Product_Category
Electronics    11
Clothing       10
Home           10
Beauty          9
Name: count, dtype: int64

In [ ]:
# Electronics items are most popular

# 25. Based on mean and median Order_Value, describe the typical customer order.

**Answer**

In [50]:
mean = dataset["Order_Value"].mean()
median = dataset["Order_Value"].median()

In [51]:
mean

np.float64(2815.0)

In [52]:
median

2525.0

In [ ]:
# Mean(2815.0) > Median(2815.0) Some high value orders may be pulling the mean upward.
'''So, median is often a better description of the typical customer order when there are extreme values.'''
'''Mean = Median → Typical order is around that value.
Mean > Median → Some high-value orders may be pulling the mean upward.
Mean < Median → Some low-value orders may be pulling the mean downward.'''

# 26. Write 3 short insights that a manager could understand from your analysis.

**Answer**

In [ ]:
''' 1. City Insight:

Chennai has the strongest order activity with 12 orders (30%), followed by Madurai with 10 orders (25%).

2. Product Category Insight"

Electronics is the most popular product category with 11 orders (27.5%), indicating the highest demand among the four categories.

3. Customer & Order Insight"

The typical order value is ₹2,525 based on the median, while the mean of ₹2,815 suggests that some higher-value orders are increasing the average.'''