<a href="https://colab.research.google.com/github/Monisha1205/google_colab_quanqual/blob/main/frequency.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Placement.csv to Placement.csv

In [4]:
dataset=pd.read_csv("/content/Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [5]:
dataset["ssc_p"].value_counts()

ssc_p
62.00    11
63.00    10
67.00     9
73.00     9
52.00     9
         ..
55.68     1
41.00     1
83.33     1
43.00     1
80.60     1
Name: count, Length: 103, dtype: int64

In [7]:
dataset.shape

(215, 15)

In [8]:
dataset.shape[0]

215

In [20]:
dataset["ssc_p"].value_counts().sort_index()

ssc_p
40.89    1
41.00    1
43.00    1
44.00    1
45.00    1
        ..
85.80    1
86.50    1
87.00    3
88.00    1
89.40    1
Name: count, Length: 103, dtype: int64

In [44]:
Freq_table = pd.DataFrame(columns=("unique_values", "frequency", "relative_frequency", "cumsum"))
Freq_table["unique_values"] = dataset["hsc_p"].value_counts().sort_index().index
Freq_table["frequency"] = dataset["hsc_p"].value_counts().sort_index().values
Freq_table["relative_frequency"] = Freq_table["frequency"]/dataset.shape[0]
Freq_table["cumsum"] = round((Freq_table["relative_frequency"].cumsum())*100,2)

In [45]:
Freq_table

    unique_values  frequency  relative_frequency  cumsum
0           37.00          1            0.004651    0.47
1           39.00          1            0.004651    0.93
2           40.00          1            0.004651    1.40
3           42.00          1            0.004651    1.86
4           42.16          1            0.004651    2.33
..            ...        ...                 ...     ...
92          90.90          1            0.004651   98.14
93          91.00          1            0.004651   98.60
94          92.00          1            0.004651   99.07
95          97.00          1            0.004651   99.53
96          97.70          1            0.004651  100.00

[97 rows x 4 columns]

In [46]:
Freq_table = pd.DataFrame(columns=("unique_values", "frequency", "relative_frequency", "cumsum"))
Freq_table["unique_values"] = dataset["ssc_p"].value_counts().sort_index().index
Freq_table["frequency"] = dataset["ssc_p"].value_counts().sort_index().values
Freq_table["relative_frequency"] = Freq_table["frequency"]/dataset.shape[0]
Freq_table["cumsum"] = round((Freq_table["relative_frequency"].cumsum())*100,2)

In [47]:
Freq_table

     unique_values  frequency  relative_frequency  cumsum
0            40.89          1            0.004651    0.47
1            41.00          1            0.004651    0.93
2            43.00          1            0.004651    1.40
3            44.00          1            0.004651    1.86
4            45.00          1            0.004651    2.33
..             ...        ...                 ...     ...
98           85.80          1            0.004651   97.21
99           86.50          1            0.004651   97.67
100          87.00          3            0.013953   99.07
101          88.00          1            0.004651   99.53
102          89.40          1            0.004651  100.00

[103 rows x 4 columns]

In [53]:
dataset.drop(columns = ["sl_no"], inplace=True)
dataset.head()

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [54]:
def quanqual(dataset):
  quan = []
  qual = []
  for ch in  dataset.columns:
    if dataset[ch].dtype == "O":
      #print("qual")
      qual.append(ch)
    else:
      #print("quan")
      quan.append(ch)
  return quan,qual

In [56]:
quan,qual = quanqual(dataset)

Ascending Order Works Best

*   It shows the natural flow of numbers.
*   It makes it easy to spot the lowest and highest scores.
*   It keeps cumulative frequency correct.
*   dont arrange the marks according to frequency descending when calculating cumulative frequency. That would change the meaning of cumulative frequency.

In [60]:
for ColumnsName in quan:
  Freq_table = pd.DataFrame(columns=("unique_values", "frequency", "relative_frequency", "cumsum"))
  Freq_table["unique_values"] = dataset[ColumnsName].value_counts().sort_index().index
  Freq_table["frequency"] = dataset[ColumnsName].value_counts().sort_index().values
  Freq_table["relative_frequency"] = Freq_table["frequency"]/dataset.shape[0]
  Freq_table["cumsum"] = round((Freq_table["relative_frequency"].cumsum())*100,2)
  print("\nFrequency Table for:", ColumnsName)
  print(Freq_table)

Frequency Table for: ssc_p
     unique_values  frequency  relative_frequency  cumsum
0            40.89          1            0.004651    0.47
1            41.00          1            0.004651    0.93
2            43.00          1            0.004651    1.40
3            44.00          1            0.004651    1.86
4            45.00          1            0.004651    2.33
..             ...        ...                 ...     ...
98           85.80          1            0.004651   97.21
99           86.50          1            0.004651   97.67
100          87.00          3            0.013953   99.07
101          88.00          1            0.004651   99.53
102          89.40          1            0.004651  100.00

[103 rows x 4 columns]

Frequency Table for: hsc_p
    unique_values  frequency  relative_frequency  cumsum
0           37.00          1            0.004651    0.47
1           39.00          1            0.004651    0.93
2           40.00          1            0.004651    1.40
3           42.00          1            0.004651    1.86
4           42.16          1            0.004651    2.33
..            ...        ...                 ...     ...
92          90.90          1            0.004651   98.14
93          91.00          1            0.004651   98.60
94          92.00          1            0.004651   99.07
95          97.00          1            0.004651   99.53
96          97.70          1            0.004651  100.00

[97 rows x 4 columns]

Frequency Table for: degree_p
    unique_values  frequency  relative_frequency  cumsum
0            50.0          1            0.004651    0.47
1            50.2          1            0.004651    0.93
2            50.8          1            0.004651    1.40
3            52.0          3            0.013953    2.79
4            53.0          2            0.009302    3.72
..            ...        ...                 ...     ...
84           82.0          1            0.004651   98.14
85           83.0          1            0.004651   98.60
86           84.0          1            0.004651   99.07
87           85.0          1            0.004651   99.53
88           91.0          1            0.004651  100.00

[89 rows x 4 columns]

Frequency Table for: etest_p
    unique_values  frequency  relative_frequency  cumsum
0           50.00          3            0.013953    1.40
1           50.48          1            0.004651    1.86
2           50.89          1            0.004651    2.33
3           52.00          1            0.004651    2.79
4           53.04          1            0.004651    3.26
..            ...        ...                 ...     ...
95          96.00          2            0.009302   97.67
96          96.80          1            0.004651   98.14
97          97.00          2            0.009302   99.07
98          97.40          1            0.004651   99.53
99          98.00          1            0.004651  100.00

[100 rows x 4 columns]

Frequency Table for: mba_p
     unique_values  frequency  relative_frequency  cumsum
0            51.21          1            0.004651    0.47
1            51.29          1            0.004651    0.93
2            51.45          1            0.004651    1.40
3            51.58          1            0.004651    1.86
4            52.21          1            0.004651    2.33
..             ...        ...                 ...     ...
200          74.56          1            0.004651   98.14
201          75.71          1            0.004651   98.60
202          76.18          1            0.004651   99.07
203          76.26          1            0.004651   99.53
204          77.89          1            0.004651  100.00

[205 rows x 4 columns]

Frequency Table for: salary
    unique_values  frequency  relative_frequency  cumsum
0        200000.0          6            0.027907    2.79
1        204000.0          2            0.009302    3.72
2        210000.0          4            0.018605    5.58
3        216000.0          3            0.013953    6.98
4        218000.0          2            0.009302    7.91
5        220000.0          5            0.023256   10.23
6        225000.0          1            0.004651   10.70
7        230000.0          2            0.009302   11.63
8        231000.0          1            0.004651   12.09
9        233000.0          1            0.004651   12.56
10       236000.0          2            0.009302   13.49
11       240000.0         15            0.069767   20.47
12       250000.0         18            0.083721   28.84
13       252000.0          2            0.009302   29.77
14       255000.0          1            0.004651   30.23
15       260000.0          7            0.032558   33.49
16       264000.0          1            0.004651   33.95
17       265000.0          6            0.027907   36.74
18       268000.0          1            0.004651   37.21
19       270000.0          4            0.018605   39.07
20       275000.0          5            0.023256   41.40
21       276000.0          2            0.009302   42.33
22       278000.0          1            0.004651   42.79
23       280000.0          2            0.009302   43.72
24       285000.0          1            0.004651   44.19
25       287000.0          1            0.004651   44.65
26       290000.0          1            0.004651   45.12
27       295000.0          1            0.004651   45.58
28       300000.0         22            0.102326   55.81
29       320000.0          1            0.004651   56.28
30       336000.0          1            0.004651   56.74
31       340000.0          1            0.004651   57.21
32       350000.0          3            0.013953   58.60
33       360000.0          6            0.027907   61.40
34       380000.0          1            0.004651   61.86
35       393000.0          1            0.004651   62.33
36       400000.0          4            0.018605   64.19
37       411000.0          1            0.004651   64.65
38       420000.0          1            0.004651   65.12
39       425000.0          1            0.004651   65.58
40       450000.0          1            0.004651   66.05
41       500000.0          3            0.013953   67.44
42       650000.0          1            0.004651   67.91
43       690000.0          1            0.004651   68.37
44       940000.0          1            0.004651   68.84