<a href="https://colab.research.google.com/github/Monisha1205/google_colab_quanqual/blob/main/skewness_%2C_kurtosis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#from google.colab import files
#uploaded = files.upload()

In [3]:
dataset=pd.read_csv("/content/Placement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
def quanqual(dataset):
  quan = []
  qual = []
  for ch in  dataset.columns:
    if dataset[ch].dtype == "O":
      #print("qual")
      qual.append(ch)
    else:
      #print("quan")
      quan.append(ch)
  return quan,qual

In [5]:
quan,qual = quanqual(dataset)

In [6]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [7]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [8]:
dataset.isna().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [9]:
dataset.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

In [10]:
#dataset["salary"].fillna(dataset["salary"].median(), inplace = True)

In [11]:
#dataset

In [12]:
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='median')
imp_mean.fit(dataset[quan])
SimpleImputer()
df = imp_mean.transform(dataset[quan])
df = pd.DataFrame(df,columns = quan)

In [13]:
df.head()

   sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
0    1.0  67.00  91.00     58.00     55.0  58.80  270000.0
1    2.0  79.33  78.33     77.48     86.5  66.28  200000.0
2    3.0  65.00  68.00     64.00     75.0  57.80  250000.0
3    4.0  56.00  52.00     52.00     66.0  59.43  265000.0
4    5.0  85.80  73.60     73.30     96.8  55.50  425000.0

In [14]:
x = df

In [15]:
y = dataset[qual]

In [16]:
df1 = [x,y]

In [17]:
df1

[     sl_no  ssc_p  hsc_p  degree_p  etest_p  mba_p    salary
 0      1.0  67.00  91.00     58.00     55.0  58.80  270000.0
 1      2.0  79.33  78.33     77.48     86.5  66.28  200000.0
 2      3.0  65.00  68.00     64.00     75.0  57.80  250000.0
 3      4.0  56.00  52.00     52.00     66.0  59.43  265000.0
 4      5.0  85.80  73.60     73.30     96.8  55.50  425000.0
 ..     ...    ...    ...       ...      ...    ...       ...
 210  211.0  80.60  82.00     77.60     91.0  74.49  400000.0
 211  212.0  58.00  60.00     72.00     74.0  53.62  275000.0
 212  213.0  67.00  67.00     73.00     59.0  69.72  295000.0
 213  214.0  74.00  66.00     58.00     70.0  60.23  204000.0
 214  215.0  62.00  58.00     53.00     89.0  60.22  265000.0

 [215 rows x 7 columns],
     gender    ssc_b    hsc_b     hsc_s   degree_t workex specialisation  \
 0        M   Others   Others  Commerce   Sci&Tech     No         Mkt&HR
 1        M  Central   Others   Science   Sci&Tech    Yes        Mkt&Fin
 2        M  Central  Central      Arts  Comm&Mgmt     No        Mkt&Fin
 3        M  Central  Central   Science   Sci&Tech     No         Mkt&HR
 4        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
 ..     ...      ...      ...       ...        ...    ...            ...
 210      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin
 211      M   Others   Others   Science   Sci&Tech     No        Mkt&Fin
 212      M   Others   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin
 213      F   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR
 214      M  Central   Others   Science  Comm&Mgmt     No         Mkt&HR

          status
 0        Placed
 1        Placed
 2        Placed
 3    Not Placed
 4        Placed
 ..          ...
 210      Placed
 211      Placed
 212      Placed
 213      Placed
 214  Not Placed

 [215 rows x 8 columns]]

In [18]:
pre_df = pd.concat(df1, axis = 1)

In [19]:
pre_df.head()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,265000.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed

In [20]:
pre_df.to_csv("pre_df.csv", index = False)

In [21]:
import pandas as pd

In [22]:
dataset1 = pd.read_csv("pre_df.csv")

In [23]:
dataset1 =  dataset1.drop(columns = ["sl_no"])

In [24]:
quan,qual = quanqual(dataset1)

In [25]:
quan

['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [26]:
dataset1["ssc_p"].skew()

np.float64(-0.13264949031456927)

In [32]:
skewness_kurtosis = pd.DataFrame(
    index=("skewness", "skew_type", "kurtosis", "kur_type"),
    columns=quan
)

for ColumnsName in quan:
    skewness_kurtosis[ColumnsName]["skewness"] = dataset1[ColumnsName].skew()
    skewness_kurtosis[ColumnsName]["skew_type"] = np.where(skewness_kurtosis[ColumnsName]["skewness"] < 0, "Negative skewness", np.where( skewness_kurtosis[ColumnsName]["skewness"] == 0, "Symmetric","Positive skewness") )
    skewness_kurtosis[ColumnsName]["kurtosis"] = dataset1[ColumnsName].kurtosis() + 3
    skewness_kurtosis[ColumnsName]["kur_type"] = np.where(skewness_kurtosis[ColumnsName]["kurtosis"] < 3,"Platykurtic",np.where(skewness_kurtosis[ColumnsName]["kurtosis"] == 3,"Mesokurtic","Leptokurtic"))

/tmp/ipykernel_40301/1325590217.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  skewness_kurtosis[ColumnsName]["skewness"] = dataset1[ColumnsName].skew()
/tmp/ipykernel_40301/1325590217.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  skewness_kurtosis[ColumnsName]["skew_type"] = np.where(skewness_kurtosis[ColumnsName]["skewness"] < 0, "Negative skewness", np.where( skewness_kurtosis[ColumnsName]["skewness"] == 0, "Symmetric","Positive skewness") )
/tmp/ipykernel_40301/1325590217.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  skewness_kurtosis[ColumnsName]["kurtosis"] = dataset1[ColumnsName].kurtosis() + 3
/tmp/ipykernel_40301/1325590217.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  skewness_kurtosis[ColumnsName]["kur_type"] = np.where(skewness_kurtosis[ColumnsName]["kurtosis"] < 3,"Platykurtic",np.where(skewness_kurtosis[ColumnsName]["kurtosis"] == 3,"Mesokurtic","Leptokurtic"))

In [33]:
skewness_kurtosis

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
skewness,-0.132649,0.163639,0.244917,0.282308,0.313576,4.440111
skew_type,Negative skewness,Positive skewness,Positive skewness,Positive skewness,Positive skewness,Positive skewness
kurtosis,2.39249,3.450765,3.052143,1.91142,2.529277,31.45351
kur_type,Platykurtic,Leptokurtic,Leptokurtic,Platykurtic,Platykurtic,Leptokurtic